### PR TITLE
Lets try this again

### PR DESCRIPTION
**Pull request by cjoster**
Click the fucking "merge" button!

### CODE REVIEW

**Comment by jbravo18** [comment]
I'm trying to do this all via CLI, are you wanting me to utilize the GUI on github.com?
________________________________

**Comment by cjoster** [comment]
Yeah. So I guess there was some explaining to do. Merging a branch and merging a PR are kinda different things. In the end they're both merges, but there's some difference. A normal workflow on github involves forking some repository, (optionally making a feature branch), and then making a pull request. Once the PR is there, github will tell you whether it can be merged without merge conflicts, and there's a button below this that says, "merge pull request". Click it, and it will merge the PR.

Did you add a remote pointing to my fork and merge it in on the cli and then push? But if so, how did you end up with an empty merge commit?

**Comment by cjoster** [comment]
Ahh, --no-ff?

**Comment by jbravo18** [comment]
Yes, I used CLI and  --no-f but I have no idea why, just copying and pasting commands from github. I can definitely detail the steps I took, but I don't think I can explain how for anything git related atm.

**Comment by cjoster** [comment]
Ok, do you see the "merge pull request" button on this page?

**Pull request merged**
